### ISSUE TITLE
how can I make it running under es5

### ISSUE THREAD

**Issue by klausgao** [kdex/ws-promise-client#1]
I tried:
let WS = require("ws-promise-client");
let WS = require("ws-promise-client").default;
let WS = require("ws-promise-client").Client;

but still can't work.

**Comment by klausgao** [comment]
the error is 'regeneratorRuntime is not defined',
I find the answer here 
http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await
maybe you need a babel-polyfill.
could you please make a quick fix?

**Comment by kdex** [comment]
@klausgao Thanks for reporting this. Fixed by cac62f4c69031d87bcf4ee73575c4c4861b67f19. `ws-promise-client 1.3.3` and above is now usable from ES5, too.
